### ISSUE TITLE
add release date for snip cleint

### ISSUE THREAD

**Issue by Si1kn** [Annunciate/snip-client#1]
yes add this pls thank mr si1kn

**Comment by DanterusDev** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by juker1** [comment]
big time poggers

**Comment by Annunciate** [comment]
2039.
