### ISSUE TITLE
Snip Client Website

### ISSUE THREAD

**Issue by LolTDMMMOs** [Annunciate/snip-client#2]
snipwebsite.html is spelled incorrectly.

**Comment by DanterusDev** [comment]
it's not

**Comment by LolTDMMMOs** [comment]
It is spelled "snipwebstie.html", that is incorrectly spelled.

**Comment by DanterusDev** [comment]
annunciate does not misspell

**Comment by Annunciate** [comment]
> 
> 
> annunciate does not misspell

this is factual.
