### ISSUE TITLE
create snip cosmetic

### ISSUE THREAD

**Issue by Si1kn** [Annunciate/snip-client#3]
thanks annunciate pls make snip cosmetic thank mr si1kn

**Comment by Si1kn** [comment]
@Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate @Annunciate

**Comment by Si1kn** [comment]
thanks for telling me that i am cool, i feel cool now

**Comment by Si1kn** [comment]
<3

**Comment by DanterusDev** [comment]
Yes irl cosmetics wen?

**Comment by Si1kn** [comment]
idk https://cdn.discordapp.com/attachments/770496102687440897/772992502910681098/snip_client.png

**Comment by Si1kn** [comment]
because fixed

**Comment by Annunciate** [comment]
hahahahahha so funny
